version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env_prod
    command: -p 6543
    expose:
      - 6543

  app:
    build:
      context: .
    container_name: fastapi_backend
    env_file:
      - .env_prod
    command:
      - "/backend/docker/backend.sh"
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  redis:
    image: redis:7-alpine
    container_name: redis
    command: --port 5370
    expose:
      - 5370

